### ISSUE TITLE
Nc 20 beta: ordered list no longer visible

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/text#1043]
**Describe the bug**
The numbers in an ordered list don't show up

**To Reproduce**
Create an ordered list and see the numbers not appear...  🤯

![Screenshot_20200915_161946](https://user-images.githubusercontent.com/551757/93222468-4805ed80-f76f-11ea-9aef-589da0bde19a.png)

Running on cloud.nc.c - beta 3 or so? Just pre RC. Browser: Chromium. Jan had the same issue, I think he uses Firefox.

**Comment by juliushaertl** [comment]
Seems to be coming from user_status, I'll have a look:

![image](https://user-images.githubusercontent.com/3404133/93223095-fa3db500-f76f-11ea-945f-0384f7ddaeb9.png)

**Comment by viceice** [comment]
Seeing this on v20.0.0 release too 😞

**Comment by elpraga** [comment]
Still present in NC 20.0.1

**Comment by elpraga** [comment]
**Text** should be one of the stellar Nextcloud apps and the centre/showcase if the Hub and collaboration.

It has how many? 10 Menu items? And one of them has not been working for almost two months?

I've been using Nextcloud since before it was Nextcloud, and I love it.

But, can you see the message @juliushaertl  that is being sent to people who are considering  using Nextcloud when one of very few features in one of the stock and most visible apps is not working? 

What would they think about the quality of the rest of the code?

Unfortunately, it is completely **irrelevant** if this bug actually tells anything about the quality of the rest of the code. This time, it is the impression that counts.

**Comment by elpraga** [comment]
I've just noticed that ordered lists **are rendered correctly** when using the Android app. 

Ordered lists **are not rendered correctly** in the **same files** when using Google chrome on Android or Firefox on Android or o in Google chrome on Ubuntu.

Does this information help to solve there issue @juliushaertl ?

**Comment by juliushaertl** [comment]
This was fixed in server with https://github.com/nextcloud/server/pull/23898
