### ISSUE TITLE
Add support for orgmode files

### ISSUE THREAD

**Issue by csantosb** [nextcloud/text#1052]
**Is your feature request related to a problem? Please describe.**
I manage to open and edit .txt and .md files, but not .org files. Currently, I need to rename .org to .md file names.

**Describe the solution you'd like**
At a minimum, being able to word with .org files the same way as I'm doing with .md files.

**Describe alternatives you've considered**
At some far away point in time, I have to investigate the use of organice as another option for editing .org files.

**Additional context**

**Comment by jospoortvliet** [comment]
what is a .org file? Lotus Organizer? Microsoft Origin? I'm not sure we want to add more file types, especially if there are conflicts with other apps that use the same file type...

**Comment by csantosb** [comment]
[Orgmode](https://orgmode.org/) is a broadly used [markup](https://orgmode.org/org.html#Markup-for-Rich-Contents) language, similar to markdown, but with much more extended capabilities. It would be great to have access to similar features to the existing ones, but adapted to org: headings, listings, bolds, etc.

**Comment by ParaplegicRacehorse** [comment]
I would lovelovelove to have a decent org editor for Nextcloud. Also asciidoc. I never write in markdown when I have an org-mode or asciidoc option. Because I sometimes have to edit a file on a device which is not synced, being able to work with my favorite markup syntaxes (org and asciidoc) in the NC web interface would be awesome.

Right, and also ledger/hledger/beancount, but this might be better suited as a separate NC-app.  :grin:

This is related to #394

**Comment by juliushaertl** [comment]
This is out of scope of the text app. We aim to provide a visual editor and are using markdown mainly because it comes with the benefit of having a easily readable plaintext file that also works when opening it outside. Supporting a parsing and serializing a rich formatted document to a different format is currently not on our roadmap.

**Comment by juliushaertl** [comment]
For opening org mode files in plain text editing mode see https://github.com/nextcloud/text/issues/394
