### ISSUE TITLE
Direct editing breaks with internal links

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/text#1169]
![image](https://user-images.githubusercontent.com/3404133/98968318-d26b9300-250d-11eb-95eb-27ee4041151c.png)

**Comment by juliushaertl** [comment]
Found when looking into https://github.com/nextcloud/android/issues/7192

**Comment by paulRbr** [comment]
Hi there, this bug is easy to reproduce:

- create a new markdown file
- Type some text then use the nextcloud text editor to add an internal link by selecting the text and hitting the button « link to a file » and choose a NC file to link
- Share the markdown file with a public link
- Open the public link and the file preview will not render and the following error will be present in the JS console:
```
Failed to update steps in collaboration plugin TypeError: OCA.Viewer is undefined
```

(I commented here to add the text of the error in case some people search for it through a search engine)

**Comment by matthijskooijman** [comment]
I also ran into this editor. Unlike what the title suggests, for me it also breaks when *viewing* a markdown file through a read-only share link.

Looking at the generated HTML, it seems that the javascript file for the `viewer` app is not included in the page, which explains why `OCA.Viewer` is not available. Maybe there is a missing dependency in this app somewhere (not sure how this stuff works, though). It seems that when editing the markdown file through the regular edit interface (i.e. when logged in), the viewer app js *is* included in the `<head>` (maybe because some other app that is also used in this view *does* declare the dependency correctly or so?):

    <script nonce="" defer="" src="/apps/viewer/js/viewer-main.js?v=855d4adb-3"></script>

**Comment by Raudius** [comment]
When opening the file in the direct edit/public view we dont have access to the files app and the user might not even be logged in.

Steps to fix
- [ ] Dont assume OCA.Viewer is available in `src/helpers/links.js#domHref`
- [ ] Forward opening of URL in window, will redirect the user to `/login` if not logged in
