### ISSUE TITLE
Migrate to tiptap v2

### ISSUE THREAD

**Issue by juliusknorr** [nextcloud/text#1906]
Might need some additional evaluation to see what we actually need to change, especially with the custom marks/blocks and the collaboration/annotation plugins, but i think we should at some point consider an upgrade.

https://tiptap.dev/overview/upgrade-guide

**Comment by azul** [comment]
As a start i will summarize considerations from the last time we talked about this.

## Why upgrade:
* stay up to date with our dependencies
* new, cleaner codebase
* benefit from new features and plugins
* longer term compatibility for things we develop ourselves
* Collaborative editing is fairly slow right now. Faster sync times of doc status would be nice.

## Challanges with the Collaboration plugin
* We need a way to sync clients that can be deployed on a plain LAMP stack.
* WebRTC might not work because of lack of turn server in certain network setups
* We need to save the state of the document to the file storage
* Optionally improve performance with non LAMP addition

## Possible approaches

### Forward port the old collaboration plugin to tiptap2

We have a working collaboration plugin for tiptap1 - forward port it to tiptap2.
Would be the closest to what we have so far.

pros:
* no need to change server code
* should be pretty straight forward
* maybe reusible for other projects in a similar situation
* known to work on LAMP stack
* Would work in all deployments
* Could be used as a fallback

cons:
* cannot use tiptap2 plugin as is
* not possible to combine with webRTC
* no performance improvements
* no Y.js merges

### PHP implementation of Y.js server side

pros:
* easy to integrate with nextcloud file storage
* Would work in all deployments

cons:
* not sure if this is possible at all
* Might be cumbersome to write performant async code in php

### Rust implementation of Y.js as part of the notify_push app

pros:
* Rust (type safety, high performance, async primitives)
* Rust implementation of Y.js is on the way
* push_notify is already written in rust and promoted as "high performance backend"

cons:
* Requires fallback for LAMP deployment
* Maybe harder to integrate with storage (but notify_push already connects to the storage)

### Deploy Y.js server

pros:
* No need to (partly) develop a Y.js server.
* easy to deploy optionally and containerize (i guess)

cons:
* Requires fallback for LAMP deployment
* We'd still need a way to store state to the files backend
