### ISSUE TITLE
(un)ordered list button not effective when the content is empty

### ISSUE THREAD

**Issue by eneiluj** [nextcloud/text#1974]
Hitting the ordered list or unordered list button does not add a first bullet point (or number) while there is no content and this is the first action.
Once there has been some edition, it works fine, even efter deleting all the content.

This happens in the browser and in the Android client.

**To Reproduce**
* Create a new markdown file
* Hit the (un)ordered list button => nothing happens
* Type some text and delete it to get an empty file again
* Hit the (un)ordered list => it works

**Comment by mejo-** [comment]
Actually this seems to be the case with any action from the toolbar. Checklist, blockquote, code block, etc. all don't work on a new document without any content. Using the markdown formatting syntax on the other hand works.

Seems like something is not fully initiallized before the document has content :thinking: 

It also happens when opening an empty but existing markdown file. So it's not related to creating a new file, but more to the file not having content yet.

Nothing relevant is logged to the JS console.

**Comment by mejo-** [comment]
Or probably there's no prosemirror node yet to align the formatting to/with :thinking:

**Comment by mejo-** [comment]
I did some further testing but didn't find the reason for this bug yet.

* reproducible if Text gets loaded by Viewer app
* reproducible for public view of single-file shares (not loaded by Viewer app)
* not reproducible in workspaces
* not reproducible in Collectives

`editor.getHTML()` returns the same content for new empty documents in all cases. Also, a quick manual comparison of the editor object didn't reveal anything obvious.

Also interesting: in scenarios where the issue is reproducible, keyboard shortcuts don't get caught by the editor at all. If they have a meaning in the browser, that one applies (e.g. for Ctrl+Shift+1). So apparently something is not registered yet properly? :thinking:

**Comment by juliushaertl** [comment]
For the keyboard shortcuts maybe there is some conflicting event handler that stops propagation in some regards, but I don't see how that would influence clicking the buttons in the same way then

**Comment by juliushaertl** [comment]
Stepped through it a bit and seems that getting the range between $from=0 and $to=0 fails:

![image](https://user-images.githubusercontent.com/3404133/144991026-f11fd02e-057c-4e3a-b2b5-7650a1a8ef68.png)

**Comment by juliushaertl** [comment]
For comparison, this is after typing one char and removing it again: 
![image](https://user-images.githubusercontent.com/3404133/144991277-4e5cabef-fa5f-4a9f-abc1-b12cfaa250a6.png)

**Comment by juliushaertl** [comment]
| Failing | Working |
|---|---|
| ![image](https://user-images.githubusercontent.com/3404133/144991510-cde0738a-24aa-4c87-862e-63c1d674193c.png) | ![image](https://user-images.githubusercontent.com/3404133/144991390-222f61b2-bc94-43fb-a5e3-f449ed0023f6.png) |

**Comment by juliushaertl** [comment]
Seems this is the culprit line: https://github.com/nextcloud/text/blob/a07fe2d32be617446d26132d87293e735452fadc/src/components/EditorWrapper.vue#L420

We only autofocus in the viewer and not on rich workspaces

**Comment by mejo-** [comment]
> Seems this is the culprit line:
> 
> https://github.com/nextcloud/text/blob/a07fe2d32be617446d26132d87293e735452fadc/src/components/EditorWrapper.vue#L420
> 
> We only autofocus in the viewer and not on rich workspaces

Indeed, good catch!

`this.tiptap.focus('start')` sets `position` to `(0, 0)`, see https://github.com/ueberdosis/tiptap/blob/v1/packages/tiptap/src/Editor.js#L374. This in turn results in `range` being empty at https://github.com/ueberdosis/tiptap/blob/v1/packages/tiptap-commands/src/commands/toggleList.js#L16, which stops `toggleList` from adding a list item.

Changing `this.tiptap.focus('start')` to `this.tiptap.focus(1, 1)` fixes the bug for me. I wonder whether that's what we want though.

**Comment by juliushaertl** [comment]
Would need some further checks on if that has any side effect with freshly opening a document with existing content, otherwise that seems sane. Or maybe we just get the range for 0,0 and only focus to 1,1 if the range is empty.

**Comment by hanspagel** [comment]
`this.tiptap.focus(1, 1)` seems to be a good workaround to me. 👌

**Comment by mejo-** [comment]
> `this.tiptap.focus(1, 1)` seems to be a good workaround to me. ok_hand

Nice, thanks a lot for confirming @hanspagel :heart_eyes:
