### ISSUE TITLE
Update CommonMark test to 0.30

### ISSUE THREAD

**Issue by vinicius73** [nextcloud/text#2217]
Now it is used [0.28 (2017-08-01)](https://spec.commonmark.org/0.28/spec.json) version of CommonMark Spec in tests.
But there are two new releases 
Actually the last version is [0.30](https://spec.commonmark.org/0.30/), and this is supported by [markdown-it](https://github.com/markdown-it/markdown-it/blob/master/test/fixtures/commonmark/spec.txt#L4)

I've tried a fast update, but some tests failed.

Also, do we really need to test it? markdown-it already test it.

**Comment by juliushaertl** [comment]
Actually 0.29 should currently be in use https://github.com/nextcloud/text/pull/861/commits/d7de7d99f1f204bbd4071dd64c51a66a11e6a80c

The reason those tests were added is mainly because text does multiple conversion steps
- markdown to html
- html to json to fit into the prose mirror schema
- prose mirror to markdown

The tests were mainly to ensure that with those different intermediate steps, we still stick to the expected format. https://github.com/nextcloud/text/blob/master/src/tests/markdown.spec.js#L25-L49

There were some test failures last time only due to additional whitespace which were skipped in the linked spec file, so might be worth to have a look at the actual failures if those are also related to that or something more serious.

**Comment by vinicius73** [comment]
Thanks for the explanation @juliushaertl 
I will take a close look at it when I can.

**Comment by susnux** [comment]
> The tests were mainly to ensure that with those different intermediate steps, we still stick to the expected format. https://github.com/nextcloud/text/blob/master/src/tests/markdown.spec.js#L25-L49

But the commonmark tests only test markdown-it, they do no test the markdown->html->markdown pipeline, that would require using `markdownThroughEditor`. So they are not that useful as `markdown-it` tests for commonmark itself.

**Comment by julien-nc** [comment]
Any news on that? @vinicius73 Do you still feel it's worth updating? If not, let's close this.
