### ISSUE TITLE
Embedded images generate links that are not markdown compatible / interoperable. Also unnecessary copys of image are created.

### ISSUE THREAD

**Issue by lars-becker** [nextcloud/text#2411]
**Describe the bug**

If I embed an image in a markdown file with Nextcloud Text *an image link is created which is not compatible with other markdown apps* **which defeats the purpose of using markdown in the first place**. The usage of Markdown was is one major reason why we started using text documents. 

**Because of this change Text effectively  becomes a product which uses a **proprietary format** that is not interoperable and can't be rendered properly outside of Nextcloud.** Cumbersome office documents are now again much more interoperable than Text in this regard. This is a highly annoying regression that renders Text almost unusable in our use case (in which people also use Markdown files on their desktops).

Also unnecessary copies of the image will be created. This *unwanted* **redundancy** increases the likelyhood that there will be confusing among users and that in later edits wrong images might be edited. This kind of magic is, from my point of view, neither user friendly nor helpful in keeping a consistent and error free documentation.
 

**To Reproduce**
1. Open a markdown file.
2. Click on Insert image and select an existing image
3. The image is inserted with a link that is not standard conform like this: `![Raumübersicht](text://image?imageFileName=1652529375-nc_bbb_raumanzeige.png`
4. Also a copy of the image is created and moved to a attachment subdirectory; which might be fine in case of a new file, but not in case of an existing file. Redundancy is bad for many reasons.

**Expected behavior**

1. Produce CommonMark compatible links.
2. Don't copy existing images.

**Text app version:** 3.5.1
**Nextcloud version:** 24.0.0

**Comment by lars-becker** [comment]
As a workaround a switch to disable the possibility for users to upload images would be nice. A downgrade to an old text version is not feasible and this feature breaks things. With such a setting only our users who are using desktop apps can create images and others can't break things unknowingly.

**Comment by allesblinkt** [comment]
I second that oppinion. Up until now we had established a very nice workflow for working on technical documents (manuals, documentation, etc.) using Text. The images for those documents already exist in a good directory structure. Then we would use *pandoc* to generate PDF output.
Text now has a couple of very nice additional features (thank you for callouts and tables), but the image handling breaks our workflow. Having a configuration switch to disable upload would be a welcome option. Alternatively, there could be a distinction between **uploaded** images and **linked** images.

**Comment by eneiluj** [comment]
Hi,

### Issues with the old image links

* In Text, an image could only be seen by users having access to the image file (accessed by file ID).
* Same in external editors, plus the relative path had to be the same for every viewer. It works fine when the .md file is in a shared directory but most likely never works with single .md files shares.
* Moving a .md file would not break images in Text (which used the file ID rather than the relative path to access images) but would break them for external editors.
* Deleted image files would still be referenced in .md files.

### Why do we now use the attachment folder? What does it bring?

* It reduces the chances to make mistakes as Text handles the image storage.
* Images are now accessed via the Text API so everyone having access to a .md file also has access to its attached images (in Text).
* Attachments are automatically moved with the .md file.
* Attachments are copied if the .md file is copied.
* Attachments are cleaned up when removed from the markdown content and when the .md file is deleted.

Regarding the image file duplication when inserting: We didn't want to implement a different behaviour between an image insertion and an image upload. Also, when someone else than the .md file owner adds an attachment, putting/copying it in the attachment folder gives everyone else access to it.

### How do we move forward?

There might be a way to keep the best of the old and the new image management:
I'm assuming we keep the attachment folder in which we put image when uploaded or inserted by Text.
Instead of inserting `text://image?imageFileName=foo.png` as the markdown image target, we could rather put `.attachments.MD_FILE_ID/foo.png?textAttachmentFileName=foo.png`. So:
* Text behaviour:
    * If `textAttachmentFileName` is there, use it to get the image with the attachment API.
    * If not, use the path (everything before the `?`) with the WebDav API.
* External editors
    * Use the path.

The external editors could still insert images with a relative path. I mean Text would still be able to render those (in some cases like mentioned before).

Downside: If the .md file is copied, its content will still contain references on the original file's attachment directory. If it's moved, the relative paths won't work anymore. In other words, referencing an attachment by its path does not resist to many common use cases. This leaves us with:
1. keep using `.attachments.MD_FILE_ID` as attachment directory names and adjust the links in the markdown content when a .md file is copied.
2. **or** use `.attachments.MD_FILE_NAME` and rename it when the .md file is renamed.
3. **or even** ignore this issue as it does not impact Text and is probably expected by people using an external editor.

I would go with 3.

@juliushaertl @mejo- @max-nextcloud @vinicius73 What do you think?

@lars-becker @allesblinkt If you have suggestions to globally improve image management, we're interested. Let's keep in mind all the possible use cases of Text.

**Comment by max-nextcloud** [comment]
Thanks @eneiluj for the writeup and @lars-becker and @allesblinkt  for bringing this up.

I like the suggestion about moving forward but would like to tweak it a bit...

> Instead of inserting `text://image?imageFileName=foo.png` as the markdown image target, we could rather put `.attachments.MD_FILE_ID/foo.png?textAttachmentFileName=foo.png`. So: 
> ...

How about:

Instead of inserting `text://image?imageFileName=foo.png` as the markdown image target, we could rather put `.attachments.MD_FILE_ID/foo.png`.

#### Text behaviour:
   
1. If the image url matches `.attachments.MD_FILE_ID/FILENAME` use FILENAME to get the image with the attachment API.
2. If the image url matches `.attachments.OTHER_FILE_ID/FILENAME`
  a. try to retrieve the image with the WebDav API.
  b. If that fails try to retrieve FILENAME with the attachment API.
  c. Maybe rewrite the url with the own file id if b. succeeds.
3. If not, use the path with the WebDav API.
4. If that fails check if the url has a fileID param and try to get the file from that. (So we keep the old behavior for old images)


With respect to moving / copying files.I agree with going with option 3. 2.b) should have text covered.

**Comment by eneiluj** [comment]
@allesblinkt @lars-becker The behaviour described by @max-nextcloud has been implemented (except 2.c.). This has been backported to stable24 which means it will be included in the next minor Nextcloud release (24.0.2?).

If you have a test/dev setup, it would be nice if you could try it and confirm it works fine with relative image links on your side.
``` bash
cd /my/dev/setup/nextcloud/apps
rm -rf text
git clone https://github.com/nextcloud/text -b stable24
```

Feel free to reopen this issue if needed.

**Comment by lars-becker** [comment]
@eneiluj Sorry, for the late reply. Was busy, but it seems less productive than you. :-) Thats great to hear. I think I might find some time tomorrow and test the release. :-)

**Comment by lars-becker** [comment]
@eneiluj Tested it with a clone and it seems to work perfectly fine! Thanks a lot for the quick fix! Only collectives doesn't display Images anymore. Will open an issue there. :-)
