### ISSUE TITLE
Enhancing Markdown editor on web

### ISSUE THREAD

**Issue by bvn13** [nextcloud/text#2629]
Version 24.0.2 June 20 2022

Hi!
Please enhance Markdown editor with features:
- tables (badly needed)
- syntax highlighting for code (it is not possible to specify it with ```java, e.g.)
- link editing (isn't it possible to change link label)
- underscoring text (why don't you add it at the beginning?)

**Comment by mejo-** [comment]
Dear @bvn13,

Text supports tables since Nextcloud 24. Are you sure that you're on Nextcloud 24?

Link editing is supported by simply changing the text of the link in question. Just navigate to the text that is formatted as link and type. Doesn't this work for you?

Underscoring is also supported at least since Nextcloud 24.

Syntax highlighting indeed seems to be broken on Nextcloud 24.

**Comment by mejo-** [comment]
> Syntax highlighting indeed seems to be broken on Nextcloud 24.

Sorry, I have to correct myself. Syntax highlighting works as expected when you open a sourcecode file in Nextcloud Text. We don't have support for syntax highlighting in markdown code blocks though. If you consider this an important feature, could you open a seperate issue for that?
