### ISSUE TITLE
Attachments are formatted together with the next paragraph

### ISSUE THREAD

**Issue by max-nextcloud** [nextcloud/text#2873]
**Describe the bug**
When changing the format below an attachment it also affects the attachment itself.

**To Reproduce**
1. Open a text file
2. Upload an attachment
3. type somethign below
4. change format below - heading, list, todo list

**Expected behavior**
The attachment stays the way it is. Formatting only affects the section below

**Screencast**
[Bildschirmaufzeichnung vom 08.09.2022, 11:23:23.webm](https://user-images.githubusercontent.com/97337118/189086210-6bb44713-b605-495f-a5db-420784778032.webm)

**Comment by max-nextcloud** [comment]
I suspect attachments are inline elements and therefor form part of the next paragraph. I think they should be block elements in their own right.

**Comment by max-nextcloud** [comment]
@eneiluj Do you have an idea about this?

**Comment by vinicius73** [comment]
Seems it is related to #2868

**Comment by mejo-** [comment]
The reason is that we intentionally [set `inline: true` for image nodes](https://github.com/nextcloud/text/blob/b901530e68e32756faabde9e2b3d0dc30823d9f4/src/extensions/RichText.js#L86). Not sure whether that's a good thing though, given that images (and attachments) are complex structures with nested `div` elements anyway in our [`ImageView.vue`](https://github.com/nextcloud/text/blob/b901530e68e32756faabde9e2b3d0dc30823d9f4/src/nodes/ImageView.vue).

`inline: true` in the Image node configuration got introduced by the upgrade to TipTap2, specificially in this commit: edfbb70f1578dad76ff869b9f2ca0f3c027232d2. The commit message says:

> Tiptap v1 had inline images.
> v2 keeps them outside of paragraphs by default.
> Configure Image node to use inline images as markdownit creates inline images right now.

I'm not sure about the implications of switching to `inline: false` for image nodes (default in TipTap v2). A quick test at least fixed this bug :wink:

@max-nextcloud, @juliushaertl and @vinicius73 curious about your thoughts :blush:

**Comment by vinicius73** [comment]
As we are using _complex_ render strategies to render attachments, it can't be handled inline mode.

**Comment by mejo-** [comment]
> As we are using complex render strategies to render attachments, it can't be handled inline mode.

I agree. I wonder though, what implications switching from inline to block mode has. Given that markdown-it creates inline images, would that result in modified markdown source code after opening and closing documents with images?
