### ISSUE TITLE
Cleanup transactions

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/text#30]
After a document has been saved and all connected sessions have moved to that state, we can cleanup old transaction data.

**Comment by max-nextcloud** [comment]
The way we handle running sessions will fundamentally change when we start using y.js based collaboration.
Y.js can compress the changeset of the changes that happened since the initial loading of the document. I think we will make use of this and store it whenever we update the markdown. Such a compressed update for halve an hour editing session with 8 people takes 30k of storage. So i don't think we need to optimize beyond that point.

I think just cleaning up after the session ended together with the somewhat aggressive session expiry has served us well.

Closing this. Feel free to reopen when you think we should still focus on this.
