### ISSUE TITLE
Cropped menu bar on small screens

### ISSUE THREAD

**Issue by XueSheng-GIT** [nextcloud/text#3368]
**Describe the bug**
On small screens or mobile devices the menu bar is sometimes cropped (icons not visible). It seems that this issue can be forced if the screen size is reduced quite fast. On my mobile devices this issue appears from time to time if text files are opened (issue cannot be forced).

**To Reproduce**
Steps to reproduce the behaviour:
1. Open a markdown (text) file
2. Resize (reduce) the window quite fast (to force this issue)

**Expected behavior**
All icons of menu bar should be accessible (at least through the "3-dots" menu), instead of hiding completely somehow.

**Screenshots**
[Cropped menu bar.webm](https://user-images.githubusercontent.com/4077683/200181312-26c2bee0-2668-4095-9d28-c4e5aa449f13.webm)

**Client details:**
 - OS: Ubuntu 22.04
 - Browser: Firefox
 - Version: 106.0.2
 - Device: Desktop

<details>
<summary>Server details</summary>

**Text app version:** 3.6.0

**Operating system:** Ubuntu 20.04

**Web server:** apache2 (2.4.54)

**Database:** mariadb (Ver 15.1 Distrib 10.3.34-MariaDB)

**PHP version:** 7.4.32

**Nextcloud version:** 25.0.1

</details>

**Comment by susnux** [comment]
For those who are interested why this happens:

This happens because some menu bar entries should be always visible (those with unset priority or `priority === undefined` here https://github.com/nextcloud/text/blob/master/src/components/Menu/entries.js ).
They will not move into the overflow menu even when the screen is too small.

It is currently not possible allow those actions to be moved into the overflow menu as they provide submenus. And submenus do not work within the overflow menu (NcActions do not work within NcActions).

**Comment by schnillerman** [comment]
Is this the same topic?

![Screenshot_20240821_110926_Firefox](https://github.com/user-attachments/assets/7d0c8d18-e5a5-4b27-8520-170a623e41a2)

The top menu is hidden behind the file name display in both mobile and desktop view.

**Comment by susnux** [comment]
@schnillerman no please open a new issue about that

**Comment by mejo-** [comment]
To my knowledge the original issue described here was fixed in the meantime. What @susnux described above still applies, but the always visible menu items should fit even on small screens. And the problem with resizing manually got fixed. @XueSheng-GIT please let us know if you still encounter it.

**Comment by XueSheng-GIT** [comment]
@mejo- Issue is fixed. Thanks for taking care 👍.
