### ISSUE TITLE
collectives: link to a page

### ISSUE THREAD

**Issue by punkyard** [nextcloud/text#3507]
Hi
in order to create faster direct links in Collectives, could we reach for a direct link for each page?
in the 3-dot menu, in which there is 'add emoji' 'add subpage'? for exemple

It would be helpful/faster when creating links in between Collectives pages - for example.
Or when sharing a link to a specific page amongst an entire Collective.

At the moment, I need to copy the Collective's weblink in a new browser, navigate to the desired page, copy the link from the browser field (https://cloud.myweb.net/apps/collectives/p/glopglop..) to have a specific page direct link. 

Thanks for all the work on this great tool

**Comment by mejo-** [comment]
Dear @punkyard, thanks for your feedback. Did you know that you can just drag and drop a page from the page list into the editor in order to add a link to it? Is this sufficient for you?

Also, this issue is about Collectives, not about Text. So please report the issue over there if you still see room for improvement there.
