### ISSUE TITLE
invisible links

### ISSUE THREAD

**Issue by punkyard** [nextcloud/text#3559]
**Describe the bug**
using NC25 dark mode, links are black on a black background
which makes them unreadable

**To Reproduce**
1. use dark mode in Appearance
2. open text, write words, select one word, add a link
3. the text can't be read because of the colour

**Expected behavior**
link with a different colour than the background

**Screenshots**

![Capture d’écran 2022-12-11 à 13 34 42](https://user-images.githubusercontent.com/59349105/206904117-754ccece-ea12-4dab-9c33-4e51ffbd0a5a.png)

**Client details:**
 - OS: ubuntu 22.04
 - Browser:
 - safari: 14.1.2 (14611.3.10.1.7)
 - brave: 1.46.134
 - macbook pro

**Text app version: 3.6.0** 

**Operating system: macos mojave**

**Web server: ubuntu 22.04**

**Database: mariadb**

**PHP version: 8.1**

**Nextcloud version: 25.0.2.3** (see Nextcloud admin page)

</details>

**Comment by susnux** [comment]
Did you set up a different background?
Meaning within the appearances settings, did you setup e.g. "custom color" and selected black?

Because links are formatted using the "primary color" which defaults to blue, but if you change the background to a custom color it takes that color as primary color and will display links using black color.

In this case you can simply use a different primary color to fix this issue for you (btw you should also have folders be displayed using the selected color).

**Comment by punkyard** [comment]
yes, well, that's what is was. I put it to blue.
But then the colour can't be chosen..

**Comment by susnux** [comment]
I understand what you mean, setting the background color might not set the primary color to the same value, so maybe you want to report this upstream at https://github.com/nextcloud/server/issues
