### ISSUE TITLE
Syntax highlighting doesn't work in code blocks in markdown

### ISSUE THREAD

**Issue by mejo-** [nextcloud/text#3618]
In GitLab by @theroch on Nov 10, 2022, 09:20

If we enter code blocks in collectives the syntax highlighting doesn't work:
![Screenshot_2022-11-10_091802](https://gitlab.com/collectivecloud/collectives/uploads/47349d47071b4613505c1bfdba8a5023/Screenshot_2022-11-10_091802.png)

If we open the same file via the files tab with the files text editor,
![Screenshot_2022-11-10_091754](https://gitlab.com/collectivecloud/collectives/uploads/e7a562f3e17e26191dedf582c60b8c67/Screenshot_2022-11-10_091754.png)

syntax highlighting works properly:
![Screenshot_2022-11-10_091805](https://gitlab.com/collectivecloud/collectives/uploads/3825319e7c6590b4e384b6267d78ad4f/Screenshot_2022-11-10_091805.png)

**Software Versions:**

- Firefox 106.x
- Nextcloud 24.0.7
- Collectives 1.5.1

**Comment by juliushaertl** [comment]
Last time I checked a while ago (before the move to tiptap v2) this was tricky due to the fact that we'd need to preload all highlight.js syntax files that we want to support. I couldn't find a working way to avoid that, but things might have changed in the meantime.

**Comment by susnux** [comment]
This is something I already noticed some time ago and tried to fix, but currently it only works if you edit the file after loading the file, as the tiptap lowlight plugin is only triggered if the content changed.
(So loading the file -> load needed highlight.js code -> edit file & trigger content changed -> tiptap refreshes the decorations).

I do not see an easy way to do this without changing tiptap :/

**Comment by CWempe** [comment]
I tried Collectives for the first time today, because I am looking for such a tool in my home projects.

And I immediately stumbled upon the missing syntax highlighting.

I understand this might be difficult.
But please put this on the road map.

Maybe this is even a feature that should be listet in https://github.com/nextcloud/collectives/issues/482.

It seems like almost all the other solutions do support this:

https://confluence.atlassian.com/doc/code-block-macro-139390.html
https://www.bookstackapp.com/blog/beta-release-v0-25-2/#code-block-updates
https://www.notion.so/de-de/help/code-blocks
https://extensions.xwiki.org/xwiki/bin/view/Extension/EditorTools/Syntax%20Highlighting%20Application
https://community.coda.io/t/code-block-syntax-highlighting/1214/35 (not yet)

**Comment by max-nextcloud** [comment]
My understanding is that either highlight js or lowlight js come with a set of frequently used languages and then a long set of all supported languages.
I wonder if we could limit syntax highlighting to the frequently used languages and preload them.

**Comment by juliushaertl** [comment]
Yes, this seems reasonable as a easy way.

More complex but might be nice would be to seee if we can dynamically extend the loaded languages and trigger a rerender of the code block:

https://github.com/nextcloud/text/commit/1fc013c47b98123261140c0acaec173f6d47f096#diff-dc0ffe297168396604403a9825d43ae7a4cae86885f947a3191c71b6f028e66bR53-R54

**Comment by max-nextcloud** [comment]
Exactly. It's available in 26.0.5 and 27.0.2.

**Comment by theroch** [comment]
We've tested it now on 27.0.2. The syntax highlighting is working in edit mode but in the view mode it doesn't.
Should I open another issue or does it belong to this issue?

**Comment by max-nextcloud** [comment]
@theroch It's fixed in text but we need to release a new version of collectives with that uses the new version of text for view mode.
We're working on it and the fix will automatically land in collectives then.
So please open a new issue in collectives to document this is still missing.
