### ISSUE TITLE
URLs in heading do not work in readonly mode

### ISSUE THREAD

**Issue by 42ske** [nextcloud/text#3822]
**Describe the bug**
URLs in headings do not work in read-only mode. If you click at them nothing happens. If you open the same file with write permissions in the Text-App via Files everything works as expected.

**To Reproduce**
1. Go to Collectives
2. Insert an URL an format it as heading (h1, h2, …)
3. try to open the URL by clicking to it.
4. error: nothing happens

**Expected behavior**
I would expect a new browser tab to be opened with the URL as it ist if you open it from within the Text-App.

**Client details:**
 - OS: macOS, iOS, iPadOS
 - Browser: Firefox, Safari
 - Version: latest versions of OS as well as Browser
 - Device: iMac M1, iPhone SE 2022, iPad Pro 11" 3rd generation

<details>
<summary>Server details</summary>

**Collectives app version:** (see Nextcloud apps page)
2.2.1

**Operating system:**
**Web server:**
**Database:**
**PHP version:**
reproduced the bug on different servers.

**Nextcloud version:** (see Nextcloud admin page)
25.0.3

</details>

**Comment by mejo-** [comment]
This issue also exists in readonly shares of Text app, thus transfering it to nextcloud/text.

**Comment by mejo-** [comment]
For some reason, `pos` [here](https://github.com/nextcloud/text/blob/main/src/plugins/link.js#L10) doesn't point to the marked link. If I increment `pos` by one in the debugger, the link is correctly extracted.

**Comment by mejo-** [comment]
The reason for this bug is that our heading anchor links span over the whole headline in readonly mode. That's why they overlay possible links in the heading.

So I see two options here:

a) Limit width of heading anchor to `1em` in readonly mode - just [as it's done in editable mode](https://github.com/nextcloud/text/blob/7a3658a8c2eaf8f13aa7bd49a79174a5eecb24d8/src/nodes/Heading/HeadingView.vue#L118) already.
b) Accept that links in headings don't work in readonly mode.

I'm in favour of option a. What do others think @susnux @max-nextcloud @juliushaertl? Also @jancborchardt and @nimishavijay?

**Comment by susnux** [comment]
I am also in favor of option A: Users will not be disappointed by not working links in headers (as they can be added they should work).
