### ISSUE TITLE
Automatically open right sidebar if other collaborators in document

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/text#395]
If you open a Text document which already has other collaborators in it, we could directly open the sidebar with the Chat tab active so you could directly start discussing.

What do you think @juliushaertl?

**Comment by bertrand-benoit** [comment]
Since last Nextcloud 18.3+ update, the sidebar is systematically opened (although I'm the only one using my own Cloud), which is truly boring. Is there any setting allowing to disable this behaviour?
Thanks.

**Comment by jancborchardt** [comment]
Yep, opening the sidebar in Text by default is indeed quite annoying if you are the only one anyway.

@juliushaertl can we change this to only happen for documents which are shared?

**Comment by bertrand-benoit** [comment]
In the meantime, I switched back to "old" text editor + Markdown plugin.

**Comment by mejo-** [comment]
@jancborchardt so contrary to its title, the issue is about *not* opening the sidebar automatically, right?

I'm not sure what "to only happen for documents which are shared" means. Do you mean that the sidebar should be opened if the document got shared to you by somebody else? Or if you shared the document? Or in both cases? To be honest I don't see the advantage of automatically opening the sidebar in either of these cases. To always see the activity tab? I'd still say that only a small fraction of (collaborative) Text users would be interested in that. My suggestion would be to disable opening the sidebar automatically altogether :wink:

**Comment by jancborchardt** [comment]
The original text summarizes it quite well:

> If you open a Text document which already has other collaborators in it, we could directly open the sidebar with the Chat tab active so you could directly start discussing.

The comments inbetween were just because of a bug which opened the sidebar generally.

---

However, I meanwhile also agree with you, it's better to be consistent always and not show the sidebar by default. You might already be in a Talk conversation with others for example. :)
