### ISSUE TITLE
continually loses connection & makes cloud inaccessible

### ISSUE THREAD

**Issue by dddddddavid** [nextcloud/text#403]
**Describe the bug**
I get about five words in, and the trying to connect message starts appearing. after around a minute, my entire nextcloud and domain is completely inaccessible.

I can only regain access by restarting my home router.

**To Reproduce**
1. open or create document
2. start typing
3. Network connection error flashes up repeatedly
4. continue typing
5. try to do anything else in my nextcloud, or access it in another tab or browser
6. nextcloud times out with a "This site can’t be reached"
cpanel file manager also times out - before returning 'Data error.'
cpanel no longer responds at all
7.reset my home or mobile router
8. repeat with same results

cpanel file manager also times out - before returning 'Data error.'
cpanel no longer responds at all

This only happens with the Text app

**Expected behavior**
Be able to create and edit documents. Have my nextcloud not time out

**Screenshots**

**Client details:**

my nextcloud is hosted on godaddy with cPanel.

 - OS: Ubuntu 18.04.2 LTS
 - Browser: Opera 64.0.3417.92 and firefox 70.0.1 (64-bit)

<details>
<summary>Server details</summary>

can't use the issue template as not able to host onlyoffice or collabora on godaddy/cpanel

**Text app version:** (see Nextcloud apps page)
1.02

**Operating system:**
Ubuntu 18.04.2 LTS
**Web server:**
cirrus.myprivatecloud.uk
**Database:**
MySQL
**PHP version:**
7.2

**Nextcloud version:** (see Nextcloud admin page)

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
[error_log (2).txt](https://github.com/nextcloud/text/files/3820251/error_log.2.txt)

Log doesn't show *anything* at the time this happened
![Screenshot from 2019-11-07 15 10 23](https://user-images.githubusercontent.com/57491766/68400966-d6cdd500-0170-11ea-8903-3cf9d8578657.png)
)



```

#### Browser log
```
Insert your browser log here, this could for example include:

[firefox_browser_log.txt](https://github.com/nextcloud/text/files/3820289/firefox_browser_log.txt
```

</details>

**Comment by juliushaertl** [comment]
According to the error log, your MySQL server has a connection limit that blocks the queries due to a maximum number of users connected: 

```
[05-Nov-2019 17:26:18 UTC] PHP Fatal error:  Uncaught Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occurred in driver: SQLSTATE[42000] [1226] User 'davidstelephone' has exceeded the 'max_user_connections' resource (current value: 30) in /home/wpcoifvxf8ue/public_html/cirrus/lib/private/DB/Connection.php:64
```

There is not much we can do here in text or Nextcloud. This might occur since text does frequent requests however the connection should always be closed once the php execution from one request ends. Maybe you can reach out to your hosting provider to increase the limit?

**Comment by dddddddavid** [comment]
Hi Julius, thanks for the reply. Could you remove my cloud address / username from the response please.

**Comment by juliushaertl** [comment]
Sure, done

**Comment by watschu** [comment]
I recently ran into the same issue, but presumably caused by a different root:

At my server, the apache2 mod_evasive is enabled - This module is intended for preventing dos and ddos attacks (and more).

The problem with the Nextcloud-Text-App seems to be, that it sends a request to the server on each key press.

Dirty workaround, just for figuring out the cause:
disable every connection limitation (in my case disable mod_evasive) 

Supposed solution: 
Reduce the frequency of requests by waiting for 3 seconds no input and/or send a request only at every 10 typed characters.

I think the relevant code is located in the EditorWrapper [onUpdate](https://github.com/nextcloud/text/blob/deeaf736b5de129f31eaf84b615de65172cff838/src/components/EditorWrapper.vue#L302) and in the SyncService [sendSteps](https://github.com/nextcloud/text/blob/deeaf736b5de129f31eaf84b615de65172cff838/src/services/SyncService.js#L173)


I hope I this helps to improve your great work.
