### ISSUE TITLE
Hide user cursors

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/text#4126]
User cursors might be in the way for reading text. Ideally we only show the names on hover or when people are editing. Other than that a checkbox to disable them in the collaborator menu might be worth as well.

What do you think @max-nextcloud @nimishavijay ?

**Comment by mejo-** [comment]
I like the idea to always show the cursors but only display the names on hover and while they're typing (with a timeout, maybe something like 3-5 seconds).

**Comment by md-work** [comment]
Please add an option to completely disable the user cursors.

I've just been in a meeting where a lot of people were annoyed by all the user cursors blinking around (optical noise).  
And even if text was just overlapped for seconds many people were disturbed when reading text.

**Comment by max-nextcloud** [comment]
I agree it should be possible to hide them. I wonder if it would be a middle ground to only show them when people are actually typing - but that also seems harder to accomplish.

**Comment by nimishavijay** [comment]
@jancborchardt Good point about removing the setting :) 

for 1) it is enabled by default and people can switch it off from there, and for 3) it wouldn't be a per document setting, ideally? it would be a per user setting so once you unset it it would remain like that. What do you think? @max-nextcloud @mejo- would this work?

**Comment by kolAflash** [comment]
> I agree it should be possible to hide them. I wonder if it would be a middle ground to only show them when people are actually typing - but that also seems harder to accomplish.

**I think showing the user cursor labels when typing is NOT a good middle ground.**  

Maybe showing a pure colored cursor without label is OK.  
But **if there's a label it will always overlap other text. Doesn't matter if someone is typing or not.**

If you really want to have some feature like this, do it like Etherpad Lite. Coloring the text background and provide some user list view at the side.  
https://etherpad.org/img/etherpad_demo.gif

&nbsp;

Please consider:  
There's finite space. And it has to be decided how to use it.  
**You can't have everything without making compromises!**  
**I'd say first priority has to display the text, because that's why users are here for.**

And additionally:  
**Please carefully test before releasing.**  
The user cursors [caused a mess of troubles](https://github.com/nextcloud/text/issues/4100) in Nextcloud-26.0!  
**If the basics are not working stable, everything additional like users cursors becomes worthless!**
