### ISSUE TITLE
Content as Code workflow

### ISSUE THREAD

**Issue by pierreozoux** [nextcloud/text#425]
# Problem Space

As a community, I'd like to have an efficient workflow to:
 - edit a document
 - publish a document

A bit like a wiki, but
 - with a customizable html style
 - MD for editing
 - something like git for the workflow, or Nextcloud version for a starter

# Solution Space

@jmatsushita created this concept some years ago, and it is called https://iilab.github.io/contentascode/

And I think, that Nextcloud could be a nice platform to start this, again.
I don't think that this app is perfect for the job, but it could be part of the solution.

3 related issues:
 - https://github.com/nextcloud/text/issues/418 cc @robert-winkler
 - https://github.com/nextcloud/text/issues/145 cc @paulhibbitts  @brainchild0  @hugoroy  @sunjam @gary-kim  @PhrozenByte  

I'm tagging the people because I think you know what I mean, and you have around the same idea.

The workflow we are considering:
 - A main group folder for index
 - then various group folders for different teams
 - a common tag, like 'publish' to mark content as ready to be published
 - a side job that is watching a mounted webdav of the main folder and compile hugo on the fly and publish remotely
 - a button on the top right corner to edit the document and link back to Nc (editable, depending on the access of the document)

It would be kind of a mix between PicoCMS, this app, the Md app, and a possibility to manage Front Matters as a separate concern.

But when you consider that frontmatter can become some [sort of database](https://gohugo.io/templates/data-templates/), we could also as well create a monster ;)

# Alternative considered

We looked at many alternatives for that already, you can see some discussions [here](https://github.com/iilab/contentascode/issues).

The most promising lately have been:
 - https://demo.codimd.org/ but currently lacking the group part, we already developed some kind of automated workflow to publish automaticaly [website](https://www.lamyne.org/project/cybergarden/) from it
 - https://jamstack.org/ with the netlify backend

# Additional context

This is probably not the best place to discuss that, But in the forum, I can't have the nice semantic link to other issues, and be able to ping people, so here I am.
I you like the idea, subscribe to the issue, put a 👍 and I'll let you know when we have a POC to show around. Maintainers, feel free to close this issue as a won't solve. I totally get that this app should stay simple to get started. But it should also not destroy the MD underneath ;)

**Comment by kosssi** [comment]
I make this with my customers, and I disable markdown editor on Nextcloud :'(, because frontmatter is not implemented.

My workflow:
- Create Hugo website
- Synchronize with Nextcloud
- Share content folder with my customer
- Nextcloud Client for synchronise file (customer side)
- Marktext to edit markdown locally (customer side)
- Draft label on frontmatter to deploy on preprod or prod

Being able to correctly edit a frontmatter file could simplify the operation, but already it's great. **Long live static sites**.

Devops side:
- Docker container synchronise Webdav
- Docker container push to gitea when file update
- Drone CI build site with new content
- Docker container with stats generation with goaccess every 24h
