### ISSUE TITLE
[Bug]: Can't do a tabulation in the markdown editor (.md)

### ISSUE THREAD

**Issue by azalty** [nextcloud/text#4389]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Pressing tab makes the editor focus on the 3 dots icon instead of entering a tabulation when in the markdown editor (when editing a .md file)

This prevents me from making indented unordered lists like this:

- Example
  - Example

### Steps to reproduce

1. Open a .md file
2. Press tab

### Expected behavior

Obvious enough, a tab should be entered, or it should at least be able to indent a list item

### Installation method

None

### Nextcloud Server version

27

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by mejo-** [comment]
Dear @azalty, thanks for your report.

Entering tab characters is unsupported intentionally, to allow tab navigation on the website.

But about your second point: in lists, the <kbd>Tab</kbd> key should indeed indent the list item if appropriate. If this this doesn't work, it's clearly a bug. Unfortunately, I cannot reproduce this myself. For me, indenting list items with the <kbd>Tab</kbd> key works as intented.

In order to further track down the bug, we'd need some additional information:

* Which browser and operating system do you use? Are you able to reproduce the bug with different browsers?
* In case you have the Collectives app installed, does the bug also happen in Text documents there, or only if you open Text documents from the Files app?
* If you share a single Text document via link and open this share in a private browser tab, are you able to indent lists with the <kbd>Tab</kbd> key there? Or does it still not work?

**Comment by Isac99** [comment]
So only occurs when editing a .md file in the File Editor app.
Works fine in the Notes and Decks apps when editing rich text.
Using Microsoft Edge Version 115.0.1901.183 (Official build) (64-bit) on Windows 11. Also have witnessed the same behaviour in Google Chrome Version 114.0.5735.248 (Official Build) (64-bit)

**Steps to reproduce:**
Create a new .md file in a folder through the web interface

1.  Create an ordered or un-ordered list
2.  Write some text
3.  Press return to create a new line
4. Press the tab button on the keyboard

Hope it helps... always happy to help out

**Example URL**
https://xxxxxxxxxxx.tv/index.php/apps/files/?dir=/Queer%20Stream/Production/Shows&openfile=15013

**Comment by juliushaertl** [comment]
List item indentation is tracked in https://github.com/nextcloud/text/issues/3493 with a possible fix in #4735
