### ISSUE TITLE
Hide rich workspace header when there is no Readme.md

### ISSUE THREAD

**Issue by Tummerhore** [nextcloud/text#4541]
Apparently, this issue has already been fixed some time ago (#3209) but seems to have re-emerged (even though now, it only shows whitespace instead of the hint "add notes...").

- Nextcloud 26.0.3
- NC Text 3.7.2
- Tested with latest versions of Firefox and Chrome.

![grafik](https://user-images.githubusercontent.com/45203603/253626586-399afa10-ea24-4887-ac89-dc88510e41e2.png)

A quick glance in the dom revealed that the whitespace container is indeed the rich text workspace. Disabling the text extension also removes the whitespace.

![grafik](https://user-images.githubusercontent.com/45203603/253627043-ea5624a9-39eb-44c6-bfec-9aef29d56292.png)

**Comment by juliushaertl** [comment]
Seems to be caused by https://github.com/nextcloud/text/commit/4d2f4fee0914ddae7ec8ed20db9dfe8f97808a74#diff-71632b16584c065ab42128d2b5d2d631bcf9512fd807a794529b9518a56a6793R206 still

For now i think we should just remove the height when no workspace is shown, a proper follow up  would be https://github.com/nextcloud/text/pull/4254#issuecomment-1592811124

**Comment by Tummerhore** [comment]
Just downloaded NC 27.1.0 with Text 3.8.0 but the ui issue is still there. Please reopen.

**Comment by mejo-** [comment]
@Tummerhore this only got fixed in the main branch so far, which will become Nextcloud 28. I agree that we should backport this to Nextcloud 27 and 26 though. @luka-nextcloud could you take care of this?
