### ISSUE TITLE
Prevent ``` in copied text

### ISSUE THREAD

**Issue by stormenergy91** [nextcloud/text#5459]
After update the version 3.9.1 now when i copy part of text that is inside at a code block, when i paste somwhere the text is always inside ```.

I could be usefull if i need to copy it a new markdown document, but in my case in the code block I have linux terminal commands and for each command now i need to past in textedit, remove the ``` chars copy again and paste to the terminal.

Is possibile to have on the contextmenu (on right click) a voice with "copy as code" and "copy as text"?

Thanks

**Comment by susnux** [comment]
I also noticed this and think it is really bad UX wise, I would expect the text to be copied as is not the source code.
Especially if only copying parts of the code block.

Can we maybe add it with different mime types? Like adding it with `text/markdown` and a plain version with `text/plain` to the clipboard?

This way you still can past markdown where supported but get the plaintext as expected otherwise.

**Comment by susnux** [comment]
BTW this is a regression of: https://github.com/nextcloud/text/pull/5212

**Comment by juliushaertl** [comment]
Thanks for reporting. This is tracked and being worked on already in https://github.com/nextcloud/text/issues/5331
