### ISSUE TITLE
Ability to insert images from local device (or link)

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/text#58]
It would be nice if it’s possible to also insert images from the local device into the document. For example:

- The image icon shows a popover having 2 options: "Image from Nextcloud" and "Image from device"
- "Image from Nextcloud" shows the current picker"
- "Image from device" shows a native file picker
- The image is uploaded in the background – we have to probably decide where to. We shouldn’t necessarily make the same mistake as in Talk and dump it into the root folder – maybe it doesn’t even need to be visible at all?

And as @juliushaertl said about remote images:

> We cannot add remote images in general because they are blocked by the CSP as mentioned in the error. So for now only images from the same domain work for that.
>
> @rullzer Does it make sense to to fetch remote images and deliver them from the local domain, similar to the proxy we have for the app store images? Or should we just block remote images for security reasons.

**Comment by brainchild0** [comment]
I would tend to think that the most useful approach is to ingest the images into the file tree that would synchronize along with the document.  Perhaps the application can create a subfolder, in the same directory as the document, for resource dependencies.

It also seems like the current approach for inserting server images, of pointing to a server URL, will cause users to struggle with broken references, because of removed resources and the inability to use on a client or to distribute from the files copied to a client.  Again, keeping everything local seems to be the best option.  Could the application write a local hard link to the external resource, or would doing so break existing design constraints for managing and synchronizing files?

**Comment by eneiluj** [comment]
@jancborchardt @nimishavijay @LukasReschke @mejo- @azul @juliushaertl 

Hey there!

There are 2 related questions:
1. Where are the images stored when they are uploaded or downloaded from a link?
2. How do we provide access and manage access control on those images?

## 1. Storing images

What do users expect? What would feel natural or easy to understand?

Options:
* In `/Text` in the markdown file owner's storage (this currently implemented like that in #1900)
    * pros: easy to implement
    * cons: all images go to the same place
* In appdata
     * pros: files are not visible in the user's filesystem
     * cons: files can't be shared or even moved with the markdown file 
* Next to the markdown file in the owner's storage
     * pros: works fine in the Collective apps as the parent folder is accessible by the collective members
     * cons: too visible for users(?) 
* In a folder next to the markdown file in the owner's storage (hidden directory maybe?)
    * pros: same as the previous one, better isolation of images between multiple markdown files
    * cons: users might delete this directory

I like the last one, the folder could be name `.MD_FILE_ID.text` to keep the link with the markdown file.
Additionally, when inserting an image "from Files", the image file could be copied in this attachment folder to make it coherent between the 3 image insertion methods.

## 2. Accessing images
Issues:
* It's rather annoying or complex for users to share the image files to everyone having access to the markdown file.
* It's currently not possible to display images when viewing a markdown file via a public link.

Options:
* When inserting, automatically share the image with everyone having access to the markdown file
     * pros: transparent for the user
     * cons: not dynamic (if the .md file is shared with additional people afterwards), does not solve the public link issue
* Add a warning when inserting an image and display a button to share it with relevant entities
    * pros: still easier than manually sharing
    * cons: require a user action, still not dynamic (except if the warning/button is displayed when needed -> which requires a heavy check), does not solve the public link issue
* Implement a Text image access API to access and insert images
     * pros: having access to a markdown file gives access to related images (no share needed), solves the public link issue
     * cons: potential security issues (how do we only give access to images that are related with the .md file?)

I like the Text image API one. If it's combined with the `.MD_FILE_ID.text` folder storing option, it can even allow image upload when accessing a .md file via a public link as this would be the target folder.
Technically it would mean the markdown written content would be a special link (`![name.png](FILE_ID)` for example) which would trigger an API call during the rendering (Can we do that? Can we change the link target on-the-fly?). On the server side, we would search for the file (by file ID) in the attachment folder.

Can this be done in a secure way? Is it ok to consider anyone having access to a .md file can get/upload files from/to the attachment folder? Even via a public link?

**Comment by eneiluj** [comment]
@nimishavijay Thanks for the feedback!

> Basically you mean add images into a hidden directory next to the .md file, and when the file is shared, automatically updating the sharing info of the image directory as well, correct?

Not exactly :grin:, Implementing Text-specific API endpoints to get images would make it possible to even avoid sharing the images. The Text app could serve the images to anyone having access to the .md file even if the image files are not shared.

All this is implemented in the `enh/58/insert-local-images-in-attachment` branch (WIP) of Text if you want to try it.

> what would happen if I tried to insert the same image twice?

Created files have the upload timestamp in their names. The second time you upload the same image: another file will be created in the attachment folder with a different name.

> what would happen if I tried to insert 2 different images with the same name?

Same here => 2 files with different names.

Other things to consider:
* What happens if the .md file is deleted? I guess the hidden folder should be deleted but this involves file hooks which can put extra load on the server.
* What happens if the .md file is moved or copied? We should move the attachment folder too. It might get tricky to keep the association between the .md file and its attachment folder in case the .md file ID changes (because the attachment folder is named `.FILEID`, this is what's used to know where to look for attachments).
* What happens if an image is removed from the .md file (while editing in Text)? I guess the corresponding image file should be deleted in the hidden folder.

**Comment by Friedbert642** [comment]
For our little town i want to have a database/List of all wayside crosses, little chappells, and bench. We want the community to contribute in checking/maintaining those assets and have infos like fotos of the state of the asset, whos just reparing a bench and how much was the cost. 
Therefore it is essential to be able to upload images through the text editor from the mobile device.
The Article of one asset should be searchable through all articles in a folder or folderstructure. Tags would be really nice.

A similar App is : Cookbook for Nextcloud
They have image upload, tags and everything is searchable
How did they solve the image upload and store problem?
If the Cookbook GUI would be redesignable by me it would be my first choice for the
task described above.
