### ISSUE TITLE
Regarding the Notes app

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/text#6]
Now the main thing we are doing with the Text app is replacing [files_texteditor](https://github.com/nextcloud/files_texteditor/) and offer a lightweight collaborative document alternative.

But we also overlap a lot with the simple [Notes app](https://github.com/nextcloud/notes). Maybe we should talk with the contributors (korelstar and stefan-niedermann) there ahead of time since it seems that when the Text app is fully fleshed out, Notes is a bit redundant. Since the design goal with Notes from the beginning was simplicity, then if the Text app is using the Viewer then it’s even _more_ simple and focused as it doesn’t even show a left sidebar.

Or what we could keep in mind for Text and / or viewer is possibly have a left list on the side which could be expanded to show other documents in the folder for quick switching?

Not entirely sure here, what do you think @juliushaertl @skjnldsv?

**Comment by jancborchardt** [comment]
Also cc @korelstar @stefan-niedermann @nextcloud/notes here. :)

**Comment by korelstar** [comment]
Yippie! :tada: I just created a (pinned) issue in the notes repository in order to provide some information for users and developers of the notes app: https://github.com/nextcloud/notes/issues/331

I'm looking forward for the first integration attempt by @juliushaertl (see https://github.com/nextcloud/text/issues/6#issuecomment-490775649). As soon as I find some time, I will have a look at the code of Text. But I doubt that it will be in the next weeks.

**Comment by sunjam** [comment]
Perhaps @pbek has some thoughts on this as the maintainer of Qownnotes.  Cheers.

**Comment by pbek** [comment]
I also think *Notes* and *Text* is overlapping but not the same, like QOwnNotes (that is a note taking app) and a Markdown editor. *Notes* and QOwnNotes should making using a lot of markdown files to take notes easier, I'm not sure *Text* does that already or should even do that...

**Comment by juliushaertl** [comment]
> I also think Notes and Text are overlapping but not the same, like QOwnNotes (that is a note taking app) and a Markdown editor. Notes and QOwnNotes should making using a lot of markdown files to take notes easier, I'm not sure Text does that already or should even do that...

The idea is more to integrate our new editor into notes, so notes is taking care of managing notes and providing a sane interface, which is more suitable for notes than a file list while you get the rich editing possibilities of the text app.

**Comment by pbek** [comment]
> The idea is more to integrate our new editor into notes, so notes is taking care of managing notes and providing a sane interface, which is more suitable for notes than a file list while you get the rich editing possibilities of the text app.

Sounds like a good idea to me :smiley:

**Comment by brainchild0** [comment]
I agree that   the concepts of *text* and *notes* might appear strongly overlapping, especially given the ongoing convergence of software components

However, it might be valuable to consider that comparing the two terms, as they have evolved recently, might be mixing metaphors.

*Text* a type of asset, in contrast to images,, audio, and so on; whereas *notes* has come to mean a way of managing assets, that favors an informal, ad-hoc organization  that makes few demands on users' thinking or planning.  A text document might be note, or might be a book that takes years to write.  Equally, a note, in the general case, might be a photograph, or an audio recording, or a photograph with a text snippet attached, or any combination of such elements.  

Notes versus files being one distinction, and asset type being another, appear to be orthogonal considerations.  A notes application should ideally handle a variety of asset types, but itself should focus on the appropriate organizational metaphors.

As such, I agree largely with the consensus, but I would emphasize the organizational approaches provided by a notes application might equally be available for other asset types.

Aside from being able to handle a variety of  media types, a notes application that excels is one that  helps the user store assets quickly and without planning, and also helps  the user to find  an asset later, despite lack of conscientious  organizational practices.  For such purposes, a metadata-based view that emphasizes fields like creation date and user-supplied tags is more helpful than a file-based view, regardless of what might be the actual backend storage means.

A simple example that gives me an idea of how useful a notes application is for my needs is to ask both of the following questions:

1.  Can I create a note with no title?
2.  Can I create two notes with the same title?

A notes application best fulfills its function if it allows both of the above.  This freedom marks  a strong contrast to a file system, in which every asset is identified by at least one unique path.  In a notes context, forcing me to choose  a unique title  at the time I create a note takes time and focus away from my other responsibilities.

Thinking to NC applications, the best user experience might be one that, as earlier suggested, provides a view of assets that is distinct from the file-based view, but that invokes appropriate players and editors supplied by other applications.  Naturally, the user experience is even better if the invocation of these components appears inside the layout of the notes application, rather than directing the browser to the external application and away from the notes environment.

**Comment by Fmstrat** [comment]
> @jancborchardt What a lot of apps in #2 (Apple Notes, Evernote, Slite) but also other note-taking software like OneNote or Google Notes have in common is that they don't use a file based approach but have a simple interface for navigating though your notes, just like how we do it with the Notes app.
> 
> I would actually say we should integrate the editor properly into the notes app, so this is our basic note taking system and the ability to edit files from the files view is the "bonus" feature. wink

Just to throw this out there, I create OwnNote back in the day which got hugely popular (still a lot of users using it in Nextcloud, but if this integration occurs they will likely tail off. One of the most commonly said things in issues was "make sure to keep both the file view and interface view."

Looking forward to the progress here as I was just about to jump in and see if I could integrate the two until I saw this conversation ;)

**Comment by Fmstrat** [comment]
Is there a branch this is being developed against?

**Comment by Fmstrat** [comment]
Sorry for the flood of comments, but as I've just gone through a little evaluation of using the existing `Notes`, using a folder of MDs with `Text`, and the different mobile apps (along with non-Nextcloud solutions), I wanted to mention a potential "method" that could simplify things:

**Could notes just be handled with a slightly altered view with tags?**
- Add a file list view option that lists the files without extensions and quick-click filters on tags
- Update `Text` to allow for renaming of filename from the editor to help with UX
- Have the `Notes` app become a "shortcut" into that view/folder (configurable)
This would basically recreate the `Notes` experience without an entirely separate interface.

**What about mobile?**
The Nextcloud Android App is already adept at editing MD files. Setting a folder to sync makes that even better. If the server hase the "shortcut" setting, show a notes icon in-app that jumps there in the same way.

**Comment by brainchild0** [comment]
>   Update `Text` to allow for renaming of filename from the editor to help with UX

A good idea in general,  it would seem, but apparently already planned (see nextcloud/viewer#15).


>    Have the `Notes` app become a "shortcut" into that view/folder (configurable)
>   This would basically recreate the `Notes` experience without an entirely separate interface.

Then would the Viewer have  a separate interface for notes?  Or would a similar interface be provided by an entirely distinct component?  The specific actions and information desired for a file view may be different than for a notes view.

**Comment by Fmstrat** [comment]
> Then would the Viewer have a separate interface for notes? Or would a similar interface be provided by an entirely distinct component? The specific actions and information desired for a file view may be different than for a notes view.

@brainchild0 I'm guessing what I'm envisioning is allowing existing tags to be categories, and simplifying the layout. For instance, if the "Notes" app altered the view (granted, I think having the left nav "Tags" option be a display/filter like in the "after" shot is a good idea regardless).

For instance...

Before (Standard files view of Notes folder):
![before](https://user-images.githubusercontent.com/971474/84809808-793c1980-afd8-11ea-852a-7c3cbeb94f69.png)

After (Notes "app" view of Notes folder):
![after](https://user-images.githubusercontent.com/971474/84809829-81945480-afd8-11ea-8146-e6137a965858.png)

Differences:
- Hidden via CSS (or altered listing):
  - File extensions
  - Thumbnails
  - Header breadcrumbs
  - Header "notes, lists, or links..."
- "Tags" is the default highlight in left nav
  - Instead of "Tags" navigating to a separate filter page, have it display the tags underneath where clicking limits the file list to files and sub-folders that contain files with the tag

**Comment by max-nextcloud** [comment]
I think this discussion has mainly shifted to the notes app. The consensus here seems to have been that it would be nice to reuse text as the editor in notes.
In the notes app discussion it [sounded more](https://github.com/nextcloud/notes/issues/331#issuecomment-751512413) like this is blocked by #593 and [current users prefer editing the markdown syntax](https://github.com/nextcloud/notes/issues/331#issuecomment-766185386) over wysiwyg.

For now I will close this issue. I'm happy to reconsider once we have a solution to #593 and maybe even a way to switch between wysiwyg and md source editing.

Feel free to reopen if you think we should continue this discussion.

**Comment by brainchild0** [comment]
> current users prefer editing the markdown syntax

It appears the sense of the idea is that in each context, the user is limited to a subset of total possible features.  Would the best solution not rather be simply one in which the same editing environment is shared by both contexts, with the user permitted to select which editing mode, and other preferences?

**Comment by max-nextcloud** [comment]
@brainchild0 I agree to your point. I hope we will get to a point where you can switch seamlessly between md and wysiwyg editing, show both at the same time and still collaborate. At that point it would be great to use the same editor in notes and files.

Right now i think we are targeting different audiences and there was (something like) a decision in notes to not use text as the editor. I hope the approaches will converge in the long run.

**Comment by brainchild0** [comment]
@max-nextcloud, In principle there is nothing to prevent separate teams from maintaining distinct notes apps, if the contributors are available, in advance of a full convergence. For example, the wysiwyg interface could be applied to a new notes app, and then later the same interface could be extended to support mode switching, such as to make the other app obsolete.   I know this approach depends on sufficient interest for making the contributions.

**Comment by brainchild0** [comment]
@max-nextcloud, The intention of my suggestion was separate front ends that would converge with the same files store.

**Comment by bagong** [comment]
May I say, in April 2025 (2.5 years later!) this is in a deplorable state, and reflects - as absurd as it seems - very badly on the overall quality of Nextcloud - something I really regret. Text-editing and note-taking are two very central aspects of such an "eco-system", and if you get this degree of overlap and subtle difference at the same time, you make users angry. As to the "Notes" app from the Android AppStore - I thought I was installing an official Nextcloud app. Nextcloud should really disallow apps that appear like genuine Nextcloud apps if they show so little intent to integrate with the overall structure, and are so buggy.

So, why cant you switch between the three modes - view, source-editing, wysiwyg-editing - with a simple shortcut - it's been said 3 years ago and it is an evident requirement. Why is there no "no distraction" mode that works cleanly with the browser's full screen functionality? Why does notes insist on a (sorry!) stupid categories system that is tied to folders (!) when there is a comprehensive tag system, and yet - why does Text not show those tags inside the text-editing-pane (f.e. in the top line, where a lot of screen estate is spoiled for a file-name and a x), and allow to edit them while writing ???

It's a shame nothing is happening here...
