### ISSUE TITLE
Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/text#6050]
Sentry reported a quite frequent console error, that only seems there since "29.0.4 RC1"

<img width="264" alt="Screenshot 2024-07-15 at 09 29 55" src="https://github.com/user-attachments/assets/6b1fc89e-d591-4a95-9ecd-7db3c26010d0">

https://nextcloud-gmbh.sentry.io/share/issue/0d2e881a7a144773a4460df9cb99acd1/

<img width="794" alt="Screenshot 2024-07-15 at 09 29 02" src="https://github.com/user-attachments/assets/bd1fe4a1-3d78-4964-8f81-3ff0cd087236">

**Comment by max-nextcloud** [comment]
This is odd. I have not been able to reproduce it locally nor on the instance in question yet.
I wonder if this is related to our cleanup of the old sessions. But missing sessions should result in a 403 and then the message to the user to please reload the page.

**Comment by max-nextcloud** [comment]
I tried to reproduce this in various ways:
* Editing with two users in the 29.0.4 version locally.
* On cloud.nextcloud.com trying various things.
* Setting up 29.0.2 locally and migrating to 29.0.4

I still failed to reproduce it. What I did run into was a situation where `sessions` was empty because during the update Nextcloud responded with a 200 maintenance page on push and sync. Even though this caused exceptions in the same function it does not seem related.

**Comment by max-nextcloud** [comment]
Looking at the code this is probably caused by the list of sessions not including any with the current id.
In this case `sessions.find` will return `undefined` and `this.currentSession` is set to `undefined`.

I see two possible causes:
1) The server responds to a sync request with a list of sessions that does not include a session with the same id as the one that was used to authenticate the request.
2) The currentSession id changed in the meantime. Maybe this even is a response to an old request that gets handled after the document changed or so. (Which might point to collectives as there one can change pages fairly quickly).

**Comment by juliushaertl** [comment]
URLs seem mostly from files, collectives is just a low amount, top most is a read only share (from the app tutorials), but could just be due to the amout of people browsing it.

**Comment by juliushaertl** [comment]
Interestingly browsers are just chromium based ones on macOS, let me see if I can catch that somewhere locally

**Comment by max-nextcloud** [comment]
uuuhhh... we have this routine to clean up old sessions during the request. That happens after auth. So maybe one can still authenticate with a session and then have it cleaned up.

**Comment by max-nextcloud** [comment]
I was able to trigger an inconsistent state by switching the network off and on again. After a while yjs will attempt to reopen the websocket, calling SyncService.open which fails to open a new connection but still continues. Afterwards sync services `_receiveSteps` fails as `this.#connection` is `undefined`.

![grafik](https://github.com/user-attachments/assets/53519c0a-11b8-4886-ac1f-0d9c2ecdda07)

This happens a few times until the editor shows the reconnect button. I suspect it's basically the polling backend continuing in the backend.

**Comment by juliushaertl** [comment]
I also couldn't trigger the issue but I noticed when opening a read only link and keeping the browser running for a while we sometimes have additional create requests without a previous close
