### ISSUE TITLE
pad is shown only half size in shared folder

### ISSUE THREAD

**Issue by jeyca** [nextcloud/text#808]
when I have a public shared folder with a file `test.md` I can open it by simple click with the editor, but its only opened half size like here:

![Screenshot_2020-05-05_20-43-38](https://user-images.githubusercontent.com/37297730/81103579-86fa7b80-8f11-11ea-943d-5986e1b60b66.png)

is this a feature or a bug?

**Comment by r34p0r** [comment]
we have the same problem, and it seems like the window, even when it only shows half of the window, it continues further down and don't show a scroll bar, so the text will be there, but can't be shown or accessed without making the whole browser window much bigger.
![image](https://user-images.githubusercontent.com/52062081/81274609-d09db000-9050-11ea-9ee6-6b8930a90e2b.png)
In the screenshot you can see the half of line 9 is cut in half and down there is still line 10 which isn't accessable, because i don't get a scroll bar.
My solution right now is to make the window bigger.

**Comment by juliushaertl** [comment]
Please fill out the issue template especially on which version this happens.

**Comment by r34p0r** [comment]
Sure:
Reproduce:
Share a folder with someone via link and then open a text.md from the folder with text.
If you open it from your own folder, the app works just fine, it's only "broken" if you open it from a shared link.

Client details:
OS: Windows 10
Browser: Chrome
Version: 81.0.4044.138 (64-Bit)
Device: Desktop

Server:
Text app version: 2.0.0
Operating system: Debian GNU/Linux 10 (buster) with Kernel Linux 4.19.0-8-amd64 on Machine with Intel i3 9100 @3,6 Ghz and 16 GB Ram
Web server: Apache 2.4.38
Database: MySQL (10.3.22)
PHP version: 7.4.3
Nextcloud version: 18.0.0

No errors in the logs as far as i can see.

If you need any more information, just tell me 😃

**Comment by juliushaertl** [comment]
I cannot reproduce this with the latest release, please try updating to 18.0.4

**Comment by jeyca** [comment]
I only yesterday installed 18.0.4, and yes the error is gone there, thx!
