### ISSUE TITLE
Call editor from other app

### ISSUE THREAD

**Issue by tektio** [nextcloud/text#884]
I am developing nextcloud-apps for internal use und used the old editor, wich could be loaded and called via javascript inside my own app. Since support for collaboration and markdown would be great, i really like to switch to the new editor, but i can't figure out how to invode it.

Is there any straight foreward solution for this task?

**Comment by juliushaertl** [comment]
As of right now you can use the viewer app to integrate opening a file in your app: https://github.com/nextcloud/viewer#add-the-viewer-to-your-app

Apart from that I'm currently working on moving the editor into a separate library at https://github.com/juliushaertl/nextcloud-text/ so that it can also be used with text that is not located in a file, but that is not ready to use yet. Anyway contributions on that side are of course also welcome.
