### ISSUE TITLE
NC 19 open Hyperlink in new Browserwindow

### ISSUE THREAD

**Issue by apg1980** [nextcloud/text#887]
Hello,

i am Using NC19 on Ubuntu 18.04 LTS with PHP 7.3, Postgresql and Apache2.
I can insert Hyperlinks within a file.md and open the Link.
Unfortunatley the Link is opened in the same Windows.
Is there a way to fix this?

Btw. Firefox is open an new Windows, but chrome etc is opening on the same window.

**Comment by azul** [comment]
Hi @apg1980 

For me in both firefox and chrome the links open in a new Tab rather than a new window. So i can switch back to the old tab easily.
If I want to open the link and stay on the page i am on i use the middle button / scroll wheel of the mouse to click it. That opens the link in a separate tab and i stay where i was.

Not sure if that's helpful - but best idea i got :grey_question:

**Comment by apg1980** [comment]
Thanks for your answer, but the most of the Users are clicking with the left mausbutton o hyperlinks.

**Comment by juliushaertl** [comment]
> For me in both firefox and chrome the links open in a new Tab rather than a new window. 

Yes. Same here, in the end opening a new window vs a new tab is browser behavior we cannot influence, since we just call window.open in JavaScript and the browser does whatever their default is there.
